<?php

namespace Database\Seeders;

use App\Models\Matrix;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class MatrixSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $matriks = [
            ['alternatif_id' => 1,'kriteria_id' => 1,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 1,'kriteria_id' => 2,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 1,'kriteria_id' => 3,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 1,'kriteria_id' => 4,'value' => 1.00,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 1,'kriteria_id' => 5,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 1,'kriteria_id' => 6,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 1,'kriteria_id' => 7,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 1,'kriteria_id' => 8,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 1,'kriteria_id' => 9,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 1,'kriteria_id' => 10,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],

            ['alternatif_id' => 2,'kriteria_id' => 1,'value' => 1.00,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 2,'kriteria_id' => 2,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 2,'kriteria_id' => 3,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 2,'kriteria_id' => 4,'value' => 1.00,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 2,'kriteria_id' => 5,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 2,'kriteria_id' => 6,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 2,'kriteria_id' => 7,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 2,'kriteria_id' => 8,'value' => 1.00,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 2,'kriteria_id' => 9,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 2,'kriteria_id' => 10,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],

            ['alternatif_id' => 3,'kriteria_id' => 1,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 3,'kriteria_id' => 2,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 3,'kriteria_id' => 3,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 3,'kriteria_id' => 4,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 3,'kriteria_id' => 5,'value' => 1.00,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 3,'kriteria_id' => 6,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 3,'kriteria_id' => 7,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 3,'kriteria_id' => 8,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 3,'kriteria_id' => 9,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 3,'kriteria_id' => 10,'value' => 1.00,'created_at' => now(),'updated_at' => now(),],

            ['alternatif_id' => 4,'kriteria_id' => 1,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 4,'kriteria_id' => 2,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 4,'kriteria_id' => 3,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 4,'kriteria_id' => 4,'value' => 1.00,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 4,'kriteria_id' => 5,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 4,'kriteria_id' => 6,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 4,'kriteria_id' => 7,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 4,'kriteria_id' => 8,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 4,'kriteria_id' => 9,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 4,'kriteria_id' => 10,'value' => 1.00,'created_at' => now(),'updated_at' => now(),],

            ['alternatif_id' => 5,'kriteria_id' => 1,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 5,'kriteria_id' => 2,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 5,'kriteria_id' => 3,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 5,'kriteria_id' => 4,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 5,'kriteria_id' => 5,'value' => 1.00,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 5,'kriteria_id' => 6,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 5,'kriteria_id' => 7,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 5,'kriteria_id' => 8,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 5,'kriteria_id' => 9,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 5,'kriteria_id' => 10,'value' => 1.00,'created_at' => now(),'updated_at' => now(),],

            ['alternatif_id' => 6,'kriteria_id' => 1,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 6,'kriteria_id' => 2,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 6,'kriteria_id' => 3,'value' => 1.00,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 6,'kriteria_id' => 4,'value' => 1.00,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 6,'kriteria_id' => 5,'value' => 1.00,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 6,'kriteria_id' => 6,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 6,'kriteria_id' => 7,'value' => 1.00,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 6,'kriteria_id' => 8,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 6,'kriteria_id' => 9,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 6,'kriteria_id' => 10,'value' => 1.00,'created_at' => now(),'updated_at' => now(),],

            ['alternatif_id' => 7,'kriteria_id' => 1,'value' => 1.00,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 7,'kriteria_id' => 2,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 7,'kriteria_id' => 3,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 7,'kriteria_id' => 4,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 7,'kriteria_id' => 5,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 7,'kriteria_id' => 6,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 7,'kriteria_id' => 7,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 7,'kriteria_id' => 8,'value' => 1.00,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 7,'kriteria_id' => 9,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 7,'kriteria_id' => 10,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],

            ['alternatif_id' => 8,'kriteria_id' => 1,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 8,'kriteria_id' => 2,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 8,'kriteria_id' => 3,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 8,'kriteria_id' => 4,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 8,'kriteria_id' => 5,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 8,'kriteria_id' => 6,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 8,'kriteria_id' => 7,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 8,'kriteria_id' => 8,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 8,'kriteria_id' => 9,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 8,'kriteria_id' => 10,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],

            ['alternatif_id' => 9,'kriteria_id' => 1,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 9,'kriteria_id' => 2,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 9,'kriteria_id' => 3,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 9,'kriteria_id' => 4,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 9,'kriteria_id' => 5,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 9,'kriteria_id' => 6,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 9,'kriteria_id' => 7,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 9,'kriteria_id' => 8,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 9,'kriteria_id' => 9,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 9,'kriteria_id' => 10,'value' => 1.00,'created_at' => now(),'updated_at' => now(),],

            ['alternatif_id' => 10,'kriteria_id' => 1,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 10,'kriteria_id' => 2,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 10,'kriteria_id' => 3,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 10,'kriteria_id' => 4,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 10,'kriteria_id' => 5,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 10,'kriteria_id' => 6,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 10,'kriteria_id' => 7,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 10,'kriteria_id' => 8,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 10,'kriteria_id' => 9,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 10,'kriteria_id' => 10,'value' => 1.00,'created_at' => now(),'updated_at' => now(),],

            ['alternatif_id' => 11,'kriteria_id' => 1,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 11,'kriteria_id' => 2,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 11,'kriteria_id' => 3,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 11,'kriteria_id' => 4,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 11,'kriteria_id' => 5,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 11,'kriteria_id' => 6,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 11,'kriteria_id' => 7,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 11,'kriteria_id' => 8,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 11,'kriteria_id' => 9,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 11,'kriteria_id' => 10,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],

            ['alternatif_id' => 12,'kriteria_id' => 1,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 12,'kriteria_id' => 2,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 12,'kriteria_id' => 3,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 12,'kriteria_id' => 4,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 12,'kriteria_id' => 5,'value' => 1.00,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 12,'kriteria_id' => 6,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 12,'kriteria_id' => 7,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 12,'kriteria_id' => 8,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 12,'kriteria_id' => 9,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 12,'kriteria_id' => 10,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],

            ['alternatif_id' => 13,'kriteria_id' => 1,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 13,'kriteria_id' => 2,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 13,'kriteria_id' => 3,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 13,'kriteria_id' => 4,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 13,'kriteria_id' => 5,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 13,'kriteria_id' => 6,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 13,'kriteria_id' => 7,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 13,'kriteria_id' => 8,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 13,'kriteria_id' => 9,'value' => 0.25,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 13,'kriteria_id' => 10,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],

            ['alternatif_id' => 14,'kriteria_id' => 1,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 14,'kriteria_id' => 2,'value' => 0.14,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 14,'kriteria_id' => 3,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 14,'kriteria_id' => 4,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 14,'kriteria_id' => 5,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 14,'kriteria_id' => 6,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 14,'kriteria_id' => 7,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 14,'kriteria_id' => 8,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 14,'kriteria_id' => 9,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 14,'kriteria_id' => 10,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],

            ['alternatif_id' => 15,'kriteria_id' => 1,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 15,'kriteria_id' => 2,'value' => 0.25,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 15,'kriteria_id' => 3,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 15,'kriteria_id' => 4,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 15,'kriteria_id' => 5,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 15,'kriteria_id' => 6,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 15,'kriteria_id' => 7,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 15,'kriteria_id' => 8,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 15,'kriteria_id' => 9,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 15,'kriteria_id' => 10,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],

            ['alternatif_id' => 16,'kriteria_id' => 1,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 16,'kriteria_id' => 2,'value' => 0.25,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 16,'kriteria_id' => 3,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 16,'kriteria_id' => 4,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 16,'kriteria_id' => 5,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 16,'kriteria_id' => 6,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 16,'kriteria_id' => 7,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 16,'kriteria_id' => 8,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 16,'kriteria_id' => 9,'value' => 0.25,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 16,'kriteria_id' => 10,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],

            ['alternatif_id' => 17,'kriteria_id' => 1,'value' => 0.25,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 17,'kriteria_id' => 2,'value' => 0.25,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 17,'kriteria_id' => 3,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 17,'kriteria_id' => 4,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 17,'kriteria_id' => 5,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 17,'kriteria_id' => 6,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 17,'kriteria_id' => 7,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 17,'kriteria_id' => 8,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 17,'kriteria_id' => 9,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 17,'kriteria_id' => 10,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],

            ['alternatif_id' => 18,'kriteria_id' => 1,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 18,'kriteria_id' => 2,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 18,'kriteria_id' => 3,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 18,'kriteria_id' => 4,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 18,'kriteria_id' => 5,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 18,'kriteria_id' => 6,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 18,'kriteria_id' => 7,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 18,'kriteria_id' => 8,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 18,'kriteria_id' => 9,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 18,'kriteria_id' => 10,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],

            ['alternatif_id' => 19,'kriteria_id' => 1,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 19,'kriteria_id' => 2,'value' => 0.25,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 19,'kriteria_id' => 3,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 19,'kriteria_id' => 4,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 19,'kriteria_id' => 5,'value' => 1.00,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 19,'kriteria_id' => 6,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 19,'kriteria_id' => 7,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 19,'kriteria_id' => 8,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 19,'kriteria_id' => 9,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 19,'kriteria_id' => 10,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],

            ['alternatif_id' => 20,'kriteria_id' => 1,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 20,'kriteria_id' => 2,'value' => 0.25,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 20,'kriteria_id' => 3,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 20,'kriteria_id' => 4,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 20,'kriteria_id' => 5,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 20,'kriteria_id' => 6,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 20,'kriteria_id' => 7,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 20,'kriteria_id' => 8,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 20,'kriteria_id' => 9,'value' => 0.50,'created_at' => now(),'updated_at' => now(),],
            ['alternatif_id' => 20,'kriteria_id' => 10,'value' => 0.75,'created_at' => now(),'updated_at' => now(),],
        ];
        Matrix::insert($matriks);
    }
}
